Update profile page
ichala/short-let-frontend pull request #26
Opened 2022-09-22 14:05 UTC by aimalamiri

## Add profile update form in the profile page

2022-09-22 17:20 UTC, d2ndjim approved these changes
@aimalamiri, Good Job 👍 
### APPROVED ✔️

2022-09-23 09:24 UTC, ichala approved these changes
✔️ Approved , good job

2022-09-23 09:32 UTC, EidHachem requested changes
Hi  @aimalamiri 👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![169786037-9f62f867-cec1-49f6-bd13-810daaadc22d](https://user-images.githubusercontent.com/91761363/191932267-c5c36f5a-7265-43d1-8950-df65668bd85b.gif)



## Highlights
- Good commit ✅ 
- All linters passed ✅ 


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the this thread if something is not 100% clear.

2022-09-23 09:32 UTC, EidHachem commented on src/Pages/Users/Profile.jsx
> +    console.log(form);
Kindly remove console logs from the submit function

2022-09-23 09:32 UTC, EidHachem commented on src/Pages/Users/Profile.jsx
> +    } else {
[Optional] After the user submits the form, it is better to clear the password fields, and maybe redirect him to the home page

2022-09-23 10:56 UTC, aimalamiri commented on src/Pages/Users/Profile.jsx
> +    console.log(form);
Nice catch! It's removed now.

2022-09-23 10:56 UTC, aimalamiri commented on src/Pages/Users/Profile.jsx
> +    } else {
It was a nice idea, I solved the issue.

2022-09-23 11:42 UTC, EidHachem approved these changes

2022-09-23 12:24 UTC, ichala approved these changes
✔️ Approved

2022-09-26 08:29 UTC, merged